### ISSUE TITLE
Icons missing

### ISSUE THREAD

**Issue by digi-tales** [multicolor-rgb/bootrap-toolbar#1]
Thank you for developement, the app works fine. Only the icons above the editors interface are missing. Looks like this:
![grafik](https://user-images.githubusercontent.com/102251136/172815426-663ff9ba-317f-46cd-906f-d3e801acf5fb.png)

The  path in the php-code leads to nowhere:

`<button class="btn mx-1 btn-light grid-12  my-1" style="width:7%"><img width="40px" src="<?php echo DOMAIN_PLUGINS.'bootstrapbar/img/col12.png';?>"></button>`

should be

`<button class="btn mx-1 btn-light grid-12  my-1" style="width:7%"><img width="40px" src="<?php echo DOMAIN_PLUGINS.'bootstrap-toolbar/img/col12.png';?>"></button>`

**Comment by multicolor-rgb** [comment]
Hi, thanks for yours opinion:) Give me few days i will fix this on next version.

**Comment by multicolor-rgb** [comment]
https://github.com/multicolor-rgb/bootrap-toolbar/raw/2.0/bootstrap-toolbar2.zip this is new version:)
